import turtle
import math
l = turtle.Turtle()
o = turtle.Turtle()
v = turtle.Turtle()
e = turtle.Turtle()
ob2 = turtle.Screen()
l.hideturtle()
o.hideturtle()
v.hideturtle()
e.hideturtle()
l.pensize(20)
o.pensize(20)
v.pensize(20)
e.pensize(20)
l.color("blue")
o.color("blue")
v.color("blue")
e.color("blue")
ob2.bgcolor("pink")
ob2.title("v")
l.speed(1)
o.speed(1)
v.speed(1)
e.speed(1)
l.up()
l.goto(-300,100)
l.down()
l.right(90)
l.fd(100)
l.left(90)
l.fd(50)
o.up()
o.goto(-200 , 0)
o.down()
o.circle(50)
v.up()
v.goto(-150, 100)
v.down()
v.goto(-100,0) #up down
v.goto(-50, 100)
e.circle(50,-270)
e.left(90)
e.fd(100)
input()